"""Quitar campo creditos de cursos

Revision ID: 1bd28bf47dd4
Revises: a6af11e46ea7
Create Date: 2026-03-05 12:37:11.887258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1bd28bf47dd4'
down_revision = 'a6af11e46ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.drop_column('creditos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creditos', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
